Add conditional throttling howto page
wso2/docs-mg pull request #44
Opened 2020-08-28 07:01 UTC by praminda

### Purpose

Add a how to page for conditional throttling.
### Issues

Fixes #

---
#### Maintainers: Check before merge
- [ ] Manual verification

2020-08-28 07:07 UTC, VirajSalaka commented
We need to mention the pilot node  in the overview right, when it comes to application throttling and subscription throttling.

2020-08-28 11:55 UTC, praminda commented
> We need to mention the eventhub in the overview right, when it comes to application throttling and subscription throttling.

Yes we need to. Didn't add anything new here since you are anyway going to change the page. Just moved the overview page and pointed to howtos.

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
> +1.  Lets create a microgateway project
```suggestion
1.  Let's create a microgateway project
```

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
> +2.  Add the API definition(s) to `petstore/api_definitions` directory. A sample open API definition can be found [here](https://github.com/wso2/product-microgateway/blob/master/samples/petstore_basic
```suggestion
2.  Add the API definition(s) to `petstore/api_definitions` directory. A sample open API definition can be found [here](https://github.com/wso2/product-microgateway/blob/master/samples/petstore_basic.yaml). Then provide the API throttling tier using the following extension at the API level.
```

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
>  9.  Finally the added configurations in `microgw.conf` would look like this.
```suggestion
9.  Finally, the added configurations in `microgw.conf` would look like this. 
```

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
> +There can be situations where a certain APIs require more granular level of throttling. Assume you want to provide limited access to a certain IP range or a type of client applications (identified by
```suggestion
There can be situations where certain APIs require more granular level of throttling. Assume you want to provide limited access to a certain IP range or a type of client application (identified by User-Agent header). For these scenarios, a simple throttle policy with API/resource level limits is not sufficient. To address complex throttling requirements as above, microgateway is capable of throttling requests based on several conditions. The following types of conditions are supported.
```

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
> +    This type of conditions will evaluate the [backend jwt](/how-tos/passing-enduser-attributes-to-the-backend-using-jwt) and check if it has a specific claim value in it to set the throttle limit.
```suggestion
    This type of condition will evaluate the [backend jwt](/how-tos/passing-enduser-attributes-to-the-backend-using-jwt) and check if it has a specific claim value in it to set the throttle limit.
```

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
> +1.  Add/Enable below configurations to enable each of the required condition type.
```suggestion
1.  Add/Enable below configurations to enable the required condition type.
```

2020-09-16 11:05 UTC, AmaliMatharaarachchi commented on en/docs/how-tos/rate-limiting/distributed-throttling.md
> +1.  Conditional throttle policies are an advance set of API and Resource level policies. Thefore you need to define the required policy to apply in the OpenAPI definition. To do that, define `x-wso2-
```suggestion
1.  Conditional throttle policies are an advanced set of API and Resource level policies. Therefore you need to define the required policy to apply in the OpenAPI definition. To do that, define `x-wso2-throttling-tier` extension with the Advance Throttle Policy name you defined in API Manager in the above step. This extension can be defined in both API and Resource levels.
```

2020-09-21 07:15 UTC, AmaliMatharaarachchi approved these changes

2020-09-21 14:03 UTC, shaniR requested changes

2020-09-28 05:30 UTC, shaniR approved these changes

2020-09-28 05:30 UTC, merged